name: Node.js Package

on:
  release:
    types: [created]

env:
  VITE_APP_LOG_EVENTS: ${{ vars.VITE_APP_LOG_EVENTS }}
  VITE_CONFIG_FILE_PATH: ${{ vars.VITE_CONFIG_FILE_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:unit
      - run: npm run build:web-docker
      - run: npm run build:web-docker:types
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@openreplyde'
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
